fix: adjust script and hook for new folder structure

diff --git a/tools/hooks/post-commit b/tools/hooks/post-commit
--- a/tools/hooks/post-commit
+++ b/tools/hooks/post-commit
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -e
 
 # Get the commit message
 export COM_MSG=`git log -n 1 HEAD --format=format:%s%n%b`
@@ -7,22 +8,25 @@ export COM_MSG=`git log -n 1 HEAD --format=format:%s%n%b`
 [[ "$COM_MSG" != "Prepare v"* ]] && exit 0
 
 # Get commit message to extract file names
-IFS=$'\n'
 export FILES=`git log --name-only -n 1`
 
 # Loop all commit message lines
 for FILE in $FILES; do
   # Skip line if it does not contain .docx file information
   [[ "$FILE" != *".docx" ]] && continue
-  
+
   # Skip if line is not an existing file
   [[ -f "$FILE" ]] || continue
 
   # Generate target file name
-  export FILE_NAME=${FILE/.docx/}
+  export BASE_FOLDER=$(dirname "$FILE")
+  export FILE_NAME=$(basename "${FILE/.docx/}")
   export VERSION_NUMBER=${COM_MSG/Prepare v/}
   export VERSION_NUMBER=${VERSION_NUMBER%"."}
-  export TARGET="document/releases/${FILE_NAME}_v${VERSION_NUMBER}.docx"
+  export TARGET="${BASE_FOLDER}/releases/${FILE_NAME}_v${VERSION_NUMBER}.docx"
+
+  echo -e "$FILE" >> C://test.txt
+  echo -e "$TARGET" >> C://test.txt
 
   # Copy file to releases folder
   cp "$FILE" "$TARGET"
@@ -37,11 +41,6 @@ for FILE in $FILES; do
   fi
 done
 
-  # Get all changed filenames
-  export CHANGED_FILES=`git log --name-only -n1`
-
-  # Loop file named
-  #for CHANGED_FILE in $CHANGED_FILES; do
-  #done
+echo "No errors found."
 
 exit 1
